version: '3'

services:
  mysql:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 654321
    volumes:
      - /root/.mysql:/var/lib/mysql
  
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"